### ISSUE TITLE
Cant compile on Arduino 1.0.5 OSX 

### ISSUE THREAD

**Issue by elmnsk** [stanleyhuangyc/ArduinoOBD#7]
Hello trying to compile megalogger project but getting this errors:
In file included from /Users/admin/Documents/Arduino/libraries/MultiLCD/MultiLCD.h:7,
                 from megalogger.ino:14:
/Users/admin/Documents/Arduino/libraries/MultiLCD/UTFT.h:178:42: error: hardware/avr/HW_AVR_defines.h: No such file or directory
In file included from /Users/admin/Documents/Arduino/libraries/MultiLCD/MultiLCD.h:7,
                 from megalogger.ino:14:
/Users/admin/Documents/Arduino/libraries/MultiLCD/UTFT.h:227: error: 'bitmapdatatype' has not been declared
/Users/admin/Documents/Arduino/libraries/MultiLCD/UTFT.h:228: error: 'bitmapdatatype' has not been declared
/Users/admin/Documents/Arduino/libraries/MultiLCD/UTFT.h:250: error: ISO C++ forbids declaration of 'regtype' with no type
/Users/admin/Documents/Arduino/libraries/MultiLCD/UTFT.h:250: error: expected ';' before '*' token
/Users/admin/Documents/Arduino/libraries/MultiLCD/UTFT.h:251: error: 'regsize' does not name a type
In file included from megalogger.ino:14:
/Users/admin/Documents/Arduino/libraries/MultiLCD/MultiLCD.h: In constructor 'LCD_SSD1289::LCD_SSD1289()':
/Users/admin/Documents/Arduino/libraries/MultiLCD/MultiLCD.h:220: error: 'P_RS' was not declared in this scope
/Users/admin/Documents/Arduino/libraries/MultiLCD/MultiLCD.h:221: error: 'B_RS' was not declared in this scope
/Users/admin/Documents/Arduino/libraries/MultiLCD/MultiLCD.h:222: error: 'P_WR' was not declared in this scope
/Users/admin/Documents/Arduino/libraries/MultiLCD/MultiLCD.h:223: error: 'B_WR' was not declared in this scope
/Users/admin/Documents/Arduino/libraries/MultiLCD/MultiLCD.h:224: error: 'P_CS' was not declared in this scope
/Users/admin/Documents/Arduino/libraries/MultiLCD/MultiLCD.h:225: error: 'B_CS' was not declared in this scope
/Users/admin/Documents/Arduino/libraries/MultiLCD/MultiLCD.h:226: error: 'P_RST' was not declared in this scope
/Users/admin/Documents/Arduino/libraries/MultiLCD/MultiLCD.h:227: error: 'B_RST' was not declared in this scope
